apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: adl-staging
  labels:
    app: nginx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 30001
  selector:
    app: nginx
  type: LoadBalancer
