apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 664865334263.dkr.ecr.ap-southeast-1.amazonaws.com/adl-lmsx:latest
        ports:
        - containerPort: 80
